packages:
  - "apps/*"
  - "packages/*"
overrides:
  ioredis: "^5.11.1"
allowBuilds:
  "@nestjs/core": true
  "@prisma/client": true
  "@prisma/engines": true
  "@scarf/scarf": false
  bcrypt: true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  protobufjs: false
